version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "meal-planner1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1b0l8zm1s7yad"
s3_prefix = "meal-planner1"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Subemail=\"dennis.apter@digia.com\""
image_repositories = []
