AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  meal-planner

  Sample SAM Template for meal-planner

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Subemail: 
    Type: String
    Default: nelli.ukkonen@brightstraining.com

Resources:
  MealPlannerDynamoDB: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        -
          AttributeName: "diet"
          AttributeType: "S"
        - 
          AttributeName: "id"
          AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "diet"
          KeyType: "HASH"
        -
          AttributeName: "id"
          KeyType: "RANGE"
      BillingMode: PROVISIONED
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
  AddClientToDatabase:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/
      Handler: addtoDB.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSNSFullAccess
      Environment:
        Variables:
          TableName: !Ref MealPlannerDynamoDB
      Events:
        AddToDB:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /addclient
            Method: get
  AddToSQS:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/
      Handler: addtoSQS.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 ? * 6 *)
  PollFromSQS:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/
      Handler: pollfromSQS.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        PollSQS:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pollfromsqs
            Method: get
  

  MySNSTopicMealPlanner:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: alias/aws/sns
  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref Subemail
      Protocol: email
      TopicArn: !Ref MySNSTopicMealPlanner
 
  MyQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: "MealPlanner"


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  group2verkkokauppaApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/addclient/"