version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::341014156608:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-11SYHNOYMVV1S"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::341014156608:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-FADRR1XCO408"
cloudformation_execution_role = "arn:aws:iam::341014156608:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1VRACM01A7P6Y"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-11n8f4thzo4r9"
image_repository = ""
region = "eu-west-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::341014156608:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-CSO6A8ED71VX"
cloudformation_execution_role = "arn:aws:iam::341014156608:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-15TNVGXX792MS"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-6md7kvggmesb"
image_repository = ""
region = "eu-west-1"
